name: vite 8.0.0
on:
  workflow_dispatch:

jobs:
  test:
    name: vite 8.0.0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Pick Vite version 8.0.0
        run: yarn set resolution "vite@npm:^6.0.0 || ^7.0.0 || ^8.0.0-0" "npm:8.0.0"

      - name: Run tests
        run: yarn vitest
